# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [3]:
import numpy as np 
ver 2.1.1

SyntaxError: invalid syntax (3381704337.py, line 2)

2) Создать нулевой вектор размера 10

In [4]:
import numpy as np

zero_vector = np.zeros(10)
print(zero_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [5]:
import numpy as np

vector = np.full(7, 7)
print(vector)

[7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [8]:
import numpy as np

even_vector = np.arange(10, 101, 2)
print(even_vector)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [7]:
import numpy as np

random_array = np.random.rand(10)

reversed_array = random_array[::-1]

print("Оригинальный массив:", random_array)
print("Развернутый массив:", reversed_array)


Оригинальный массив: [0.93495502 0.89962526 0.7732554  0.92040775 0.0404444  0.78771007
 0.0274484  0.07384762 0.68377196 0.79462166]
Развернутый массив: [0.79462166 0.68377196 0.07384762 0.0274484  0.78771007 0.0404444
 0.92040775 0.7732554  0.89962526 0.93495502]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [9]:
import numpy as np

matrix = np.arange(9).reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [10]:
import numpy as np

matrix = np.eye(4, k=1)

print(matrix)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [11]:
import numpy as np

matrix = np.full((4, 4), 7)

np.fill_diagonal(matrix, np.arange(1, 5))

print(matrix)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [12]:
import numpy as np

matrix_1 = np.tile(np.arange(5), (5, 1))
print(matrix_1)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [13]:
import numpy as np

matrix_2 = np.random.rand(10, 10)
mean_by_row = matrix_2.mean(axis=1, keepdims=True)
matrix_2_centered = matrix_2 - mean_by_row
print(matrix_2_centered)

[[ 0.23439441 -0.09354725  0.35308851  0.16807099  0.01009873  0.02824315
  -0.06090125  0.24439038 -0.30428618 -0.57955149]
 [ 0.0868446  -0.28922125  0.36153262 -0.49567549  0.19114758 -0.02436921
   0.1757328   0.08951585  0.33324646 -0.42875396]
 [-0.20883476  0.32670433 -0.20311477  0.07355882 -0.22941572 -0.36254582
   0.04955179  0.33284728 -0.03175813  0.25300699]
 [ 0.4046191  -0.0019383  -0.06925747 -0.15134308  0.12502587 -0.33423507
   0.1647625   0.25379478  0.04161483 -0.43304317]
 [ 0.10736896 -0.2464221   0.20126586 -0.00863997  0.35349067  0.26369774
   0.32833858 -0.47175565 -0.18934066 -0.33800341]
 [ 0.29547394 -0.42869123  0.08284505  0.14786159  0.09059014  0.38564224
  -0.12567851 -0.54038906  0.04593376  0.04641208]
 [ 0.04125024  0.12493053 -0.13552115 -0.43865814  0.49839038 -0.11123147
   0.09121478  0.21156134  0.02693158 -0.30886808]
 [ 0.00689364 -0.21845469  0.14011147  0.40375115 -0.39209538  0.19376574
   0.00471658 -0.40903673  0.21082766  0.05952055]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [14]:
import numpy as np

matrix_3 = np.random.rand(10, 10)
median_by_col = np.median(matrix_3, axis=0)
matrix_3_centered = matrix_3 - median_by_col
print(matrix_3_centered)

[[ 0.03816748  0.22129016  0.38536058 -0.29012747 -0.01143344 -0.23514574
  -0.10098844  0.25358456  0.06474129  0.05458288]
 [-0.5078847  -0.48294017  0.53519995 -0.1608249   0.54874999 -0.330554
   0.0849477  -0.48772003 -0.0376732   0.4385007 ]
 [-0.27608971  0.11781666 -0.28629468  0.00080715 -0.26305667  0.40994611
  -0.10434146  0.18813126 -0.121165   -0.38683434]
 [ 0.04685736  0.14062627  0.14707468  0.04074501  0.01143344  0.38266542
   0.30620669 -0.09162295  0.0376732   0.24980673]
 [-0.31714608 -0.2214158  -0.37770104 -0.12716042 -0.3444321   0.24265481
  -0.0849477   0.01755013  0.23733946 -0.29684482]
 [ 0.00640184 -0.37569281  0.38648423  0.07876345 -0.32364356 -0.3857562
   0.12341568 -0.28602653  0.25199742 -0.21637089]
 [ 0.35909122 -0.13453561  0.08225018 -0.11036335  0.29833201 -0.02276823
   0.21884588 -0.52378793  0.24600552  0.25484031]
 [-0.00640184  0.30491249 -0.38371072 -0.00080715  0.27261035 -0.18180883
  -0.15416487 -0.01051676 -0.17356804 -0.28652266]
 [ 

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [15]:
import numpy as np

matrix_4 = np.random.rand(5, 5)
max_in_rows = matrix_4.max(axis=1, keepdims=True)
min_in_rows = matrix_4.min(axis=1, keepdims=True)
matrix_4_extended = np.hstack((matrix_4, max_in_rows, min_in_rows))
print(matrix_4_extended)

[[0.26384242 0.9662023  0.57251957 0.65324754 0.38451332 0.9662023
  0.26384242]
 [0.63430479 0.20988788 0.80861023 0.32146292 0.19954508 0.80861023
  0.19954508]
 [0.19937123 0.27418528 0.63181701 0.58855315 0.77652465 0.77652465
  0.19937123]
 [0.91372824 0.91117685 0.40085462 0.98409331 0.67595558 0.98409331
  0.40085462]
 [0.041175   0.70329061 0.59701153 0.67811704 0.3487915  0.70329061
  0.041175  ]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [17]:
import numpy as np

vector = np.arange(1, 52)
odd_vector = vector[vector % 2 != 0].reshape(-1, 1)  # Нечетные числа
even_vector = vector[vector % 2 == 0].reshape(1, -1)  # Четные числа

product_matrix = odd_vector @ even_vector
print("Произведение матриц:", product_matrix)

even_product_matrix = even_vector.T @ even_vector
print("Матрица четных чисел:", even_product_matrix)

det = np.linalg.det(even_product_matrix)
print("Определитель матрицы четных чисел:", det)

if det != 0:
    inverse_matrix = np.linalg.inv(even_product_matrix)
    print("Обратная матрица:", inverse_matrix)
else:
    print("Матрица является вырожденной и не имеет обратной матрицы.")

Произведение матриц: [[   2    4    6    8   10   12   14   16   18   20   22   24   26   28
    30   32   34   36   38   40   42   44   46   48   50]
 [   6   12   18   24   30   36   42   48   54   60   66   72   78   84
    90   96  102  108  114  120  126  132  138  144  150]
 [  10   20   30   40   50   60   70   80   90  100  110  120  130  140
   150  160  170  180  190  200  210  220  230  240  250]
 [  14   28   42   56   70   84   98  112  126  140  154  168  182  196
   210  224  238  252  266  280  294  308  322  336  350]
 [  18   36   54   72   90  108  126  144  162  180  198  216  234  252
   270  288  306  324  342  360  378  396  414  432  450]
 [  22   44   66   88  110  132  154  176  198  220  242  264  286  308
   330  352  374  396  418  440  462  484  506  528  550]
 [  26   52   78  104  130  156  182  208  234  260  286  312  338  364
   390  416  442  468  494  520  546  572  598  624  650]
 [  30   60   90  120  150  180  210  240  270  300  330  360  390  4

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [18]:
import numpy as np

chessboard_matrix = np.zeros((8, 8), dtype=int)
chessboard_matrix[1::2, ::2] = 1
chessboard_matrix[::2, 1::2] = 1
print(chessboard_matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
